project:
  type: website
  output-dir: docs
  
website:
  title: "Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - Project1.qmd
      - Project-Model-Selection-Encelia.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

